/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICarbonRewards,
  ICarbonRewardsInterface,
} from "../ICarbonRewards";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "updateReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICarbonRewards__factory {
  static readonly abi = _abi;
  static createInterface(): ICarbonRewardsInterface {
    return new utils.Interface(_abi) as ICarbonRewardsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICarbonRewards {
    return new Contract(address, _abi, signerOrProvider) as ICarbonRewards;
  }
}
