/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICarbonizedCollection,
  ICarbonizedCollectionInterface,
} from "../ICarbonizedCollection";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "carbonBalanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICarbonizedCollection__factory {
  static readonly abi = _abi;
  static createInterface(): ICarbonizedCollectionInterface {
    return new utils.Interface(_abi) as ICarbonizedCollectionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICarbonizedCollection {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ICarbonizedCollection;
  }
}
