/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICarbonizedCollection,
  ICarbonizedCollectionInterface,
} from "../ICarbonizedCollection";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "carbonBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalCarbon",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICarbonizedCollection__factory {
  static readonly abi = _abi;
  static createInterface(): ICarbonizedCollectionInterface {
    return new utils.Interface(_abi) as ICarbonizedCollectionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICarbonizedCollection {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ICarbonizedCollection;
  }
}
